---
- name: Add New PVE Role {{ role.name }}
  ansible.builtin.command:
    cmd: pveum role add {{ role.name }} -privs "{{ role.privs | join(' ') }}"
  when: role_list.stdout | regex_search('│ ' + role.name | string + ' \s*│ .*') is none
  register: new_role

- name: Modify Existing PVE Role {{ role.name }}
  ansible.builtin.command:
    cmd: pveum role modify {{ role.name }} -privs "{{ role.privs | join(' ') }}"
  when: |
    (role_list.stdout | regex_search('│ ' + role.name | string + ' \s*│ .*') is not none) and
    (role_list.stdout | regex_search('│ ' + role.name | string + ' \s*│ ' + role.privs | sort(case_sensitive=True) | join(',') | string + ' \s*│') is none)
    and not new_role.changed
